[project]
name = "Convert360ToCubemap"
version = "0.1.0"
description = "Script to convert equirectangular 360 images to cubemap images"
authors = ["Maxiviper117"]
channels = ["conda-forge"]
platforms = ["win-64"]

[tasks]
conv = 'python .\app\main.py'

[dependencies]
python = "3.11.*"
streamlit = ">=1.35.0,<1.36"

[pypi-dependencies]
py360convert = "*"
opencv-python = "*"
ipykernel = "*"
matplotlib = "*"
